# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  kakaotalk-exe = {
    pname = "kakaotalk-exe";
    version = "0.0.0";
    src = fetchurl {
      url = "https://app-pc.kakaocdn.net/talk/win32/KakaoTalk_Setup.exe";
      sha256 = "sha256-3wn7zAsHW3X1gwk6l7s4TpUcmtAsJFvR1592CK6aa2M=";
    };
  };
  kakaotalk-icon = {
    pname = "kakaotalk-icon";
    version = "latest";
    src = fetchurl {
      url = "https://upload.wikimedia.org/wikipedia/commons/e/e3/KakaoTalk_logo.svg";
      sha256 = "sha256-0N1j/BFQCtpUN3mnO8PRMpB5Xaf3Ozh7bqX+ME8kTZk=";
    };
  };
}
